import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
dotenv.config();

const engineDir = process.cwd();
const kbPath = path.join(engineDir, 'docs/knowledge-base.md');
const ragPath = path.join(engineDir, 'docs/rag-memory.json');

const COLORS = {
    reset: '\x1b[0m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    cyan: '\x1b[36m',
    red: '\x1b[31m',
    bold: '\x1b[1m'
};

async function embedText(text) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error("GEMINI_API_KEY is missing. Please add it to .env");

    const url = `https://generativelanguage.googleapis.com/v1beta/models/embedding-001:embedContent?key=${apiKey}`;
    const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            model: 'models/embedding-001',
            content: { parts: [{ text }] }
        })
    });

    if (!response.ok) {
        const err = await response.text();
        throw new Error(`Embedding failed: ${err}`);
    }

    const data = await response.json();
    return data.embedding.values;
}

async function run() {
    console.log(`\n${COLORS.bold}${COLORS.cyan}🔄 MIGRATING LEGACY KNOWLEDGE BASE TO RAG VECTOR MEMORY...${COLORS.reset}\n`);

    if (!fs.existsSync(kbPath)) {
        console.log(`${COLORS.yellow}⚠️ No legacy docs/knowledge-base.md found. Migration is not needed.${COLORS.reset}\n`);
        return;
    }

    let memories = [];
    if (fs.existsSync(ragPath)) {
        try {
            memories = JSON.parse(fs.readFileSync(ragPath, 'utf-8'));
        } catch (e) {
            console.log(`${COLORS.yellow}⚠️ Existing rag-memory.json is invalid, starting fresh.${COLORS.reset}`);
        }
    }

    const rawKb = fs.readFileSync(kbPath, 'utf-8');
    // Split by the "## Project: project-name" pattern generated by old Archivist
    const parts = rawKb.split(/## Project: /g).filter(p => p.trim());

    if (parts.length === 0) {
        console.log(`${COLORS.yellow}⚠️ Legacy knowledge base is empty.${COLORS.reset}\n`);
        return;
    }

    console.log(`Found ${parts.length} historical projects to convert. Initializing AI embedding...`);

    let addedCount = 0;
    for (const part of parts) {
        const lines = part.split('\n');
        const projectName = lines[0].trim();
        const lesson = lines.slice(1).join('\n').trim();

        if (!lesson) continue;

        // Skip if already mapped
        if (memories.some(m => m.project === projectName && m.lesson === lesson)) {
            console.log(`- Skipping ${projectName} (Already embedded)`);
            continue;
        }

        try {
            console.log(`${COLORS.cyan}- Embedding project: ${projectName}...${COLORS.reset}`);
            const embedding = await embedText(lesson);
            memories.push({
                project: projectName,
                timestamp: new Date().toISOString(),
                requirement: 'Legacy imported requirement',
                lesson: lesson,
                embedding: embedding
            });
            addedCount++;
        } catch (e) {
            console.log(`${COLORS.red}❌ Error embedding ${projectName}: ${e.message}${COLORS.reset}`);
        }
    }

    if (addedCount > 0) {
        fs.writeFileSync(ragPath, JSON.stringify(memories, null, 2), 'utf-8');
        console.log(`\n${COLORS.bold}${COLORS.green}✅ Migration successful! Added ${addedCount} lessons to Vector Memory.${COLORS.reset}`);

        const backupPath = path.join(engineDir, 'docs/knowledge-base-legacy-backup.md');
        fs.renameSync(kbPath, backupPath);
        console.log(`${COLORS.yellow}ℹ️ Old knowledge-base.md backed up to ${path.basename(backupPath)}.${COLORS.reset}\n`);
    } else {
        console.log(`\n${COLORS.bold}${COLORS.green}✅ Everything is up to date!${COLORS.reset}\n`);
    }
}

run().catch(console.error);
